### ISSUE TITLE
本机没有显卡可以跑吗？

### ISSUE THREAD

**Issue by Bryce1010** [anylots/detection#1]
![image](https://user-images.githubusercontent.com/30361513/97445460-3f0c5c80-1968-11eb-8225-8b93ce499780.png)
我可以再本地build通过，但是上传图片后就会报错
![image](https://user-images.githubusercontent.com/30361513/97445572-5e0aee80-1968-11eb-8a48-668850ac902f.png)

麻烦您看看

**Comment by anylots** [comment]
你看是不是图片太大，代码里有个1M的限制，可以改，还有有些图片格式不支持

**Comment by anylots** [comment]
可以用CPU跑
